### ISSUE TITLE
reCaptcha No Longer Supports lang Parameter, Replaced With hl

### ISSUE THREAD

**Issue by alexbeardsley** [iamthechad/grails-recaptcha#30]
This is a complete blocker and should be changed ASAP.

The reCaptcha API seems to have mysteriously and silently removed the "lang" parameter and replaced it with "hl" (that's h and lowercase L). https://developers.google.com/recaptcha/docs/display

All implementations using the lang parameter to force language no longer work.

**Comment by iamthechad** [comment]
Changing language works as expected in the 1.x versions of this plugin.

Per the docs, you need to supply the "`lang`" attribute to the `<recaptcha/>` tag. The code that creates the ReCaptcha HTML will properly set the `lang` attribute as the `hl` parameter in the captcha script tag. ([See here.](https://github.com/iamthechad/grails-recaptcha/blob/24e20ef3fd6b1ab6be370a7982c140e345b5e14b/src/groovy/com/megatome/grails/recaptcha/ReCaptcha.groovy#L110-113))

Also, per the docs, `forceLanguageInURL` is no longer supported since ReCaptcha correctly serves the specified language.
